// Code generated by ggg sync; DO NOT EDIT.
//
// index: 75a72559b76cbd4de4d87c28e9543c09e112a85cafb5b1663a574ab4004418f3
// registry: b6cc5f95d455231a98bed7931a46085a82dc638a14c9cfa244ce14fc6feaef0f

package commands

import (
	gggcli "github.com/gogogadget/gogogadget/internal/gggcli"
	ui "github.com/gogogadget/gogogadget/internal/gggcli/ui"
)

// CLICommands returns the project-local command registry contributed by the
// installed modules, in canonical name order.
func CLICommands() []gggcli.ContributedCommand {
	return []gggcli.ContributedCommand{
		{
			Spec:    gggcli.CommandSpec{Name: "ui", Summary: "Open the interactive console", Usage: "ggg ui", SourceModule: "ggg/system/cli-ui"},
			Handler: ui.Run,
		},
	}
}
