// Code generated by ggg sync; DO NOT EDIT.
//
// index: 18df62a16fbdb107136f52e39d215fa60926afccb9dcf0b1c432d71675040bdb
// registry: c587985336c5213d360d38225c718a163bc8d510ca083eb0ccac95d573ad8c19

package commands

import (
	gggcli "github.com/gogogadget/gogogadget/internal/gggcli"
	ui "github.com/gogogadget/gogogadget/internal/gggcli/ui"
)

// CLICommands returns the project-local command registry contributed by the
// installed modules, in canonical name order.
func CLICommands() []gggcli.ContributedCommand {
	return []gggcli.ContributedCommand{
		{
			Spec:    gggcli.CommandSpec{Name: "ui", Summary: "Open the interactive console", Usage: "ggg ui", SourceModule: "ggg/system/cli-ui"},
			Handler: ui.Run,
		},
	}
}
