// Code generated by ggg sync; DO NOT EDIT.
//
// index: e7916e955d3f665769b831c691bcf486324f886e31fb5b31edea0f1fbc718ec4
// registry: e8ae9086cfbc728591bef302da0802b645566ae668147c7d69f16621d4de6cd7

package commands

import (
	gggcli "github.com/gogogadget/gogogadget/internal/gggcli"
	ui "github.com/gogogadget/gogogadget/internal/gggcli/ui"
)

// CLICommands returns the project-local command registry contributed by the
// installed modules, in canonical name order.
func CLICommands() []gggcli.ContributedCommand {
	return []gggcli.ContributedCommand{
		{
			Spec:    gggcli.CommandSpec{Name: "ui", Summary: "Open the interactive console", Usage: "ggg ui", SourceModule: "ggg/system/cli-ui"},
			Handler: ui.Run,
		},
	}
}
