// Code generated by ggg sync; DO NOT EDIT.
//
// index: 6a438ae9d5d582da1e5f20f5e4dba13fe3a15fea0e936d77f712b5c587608c32
// registry: 74b03c505f06d91a3f85efb4060ad5cfbdda5849f55f061da7fe1f716e31b14f

package commands

import (
	docker "github.com/gogogadget/gogogadget/internal/database/ops/docker"
	fly "github.com/gogogadget/gogogadget/internal/deploy/fly"
	gggcli "github.com/gogogadget/gogogadget/internal/gggcli"
	neon "github.com/gogogadget/gogogadget/internal/provision/neon"
	remote "github.com/gogogadget/gogogadget/internal/remote"
)

// RemoteRegistries returns the typed provisioner, deployer, and database
// operator registries the ggg provider/deploy/db commands execute through,
// built from the target-selected contributions of the installed graph.
func RemoteRegistries() gggcli.RemoteRegistries {
	provisioners := map[string]remote.ProviderProvisioner{}
	deployers := map[string]remote.DeployTarget{}
	operators := map[string]remote.DatabaseOperator{}
	provisioners["neon_provisioner"] = neon.NewProvisioner()
	deployers["fly"] = fly.NewDeployTarget()
	operators["docker_operator"] = docker.NewOperator()
	return gggcli.RemoteRegistries{
		Provisioner: func(id string) (remote.ProviderProvisioner, bool) {
			provisioner, ok := provisioners[id]
			return provisioner, ok
		},
		DeployTarget: func(id string) (remote.DeployTarget, bool) {
			target, ok := deployers[id]
			return target, ok
		},
		DatabaseOperator: func(id string) (remote.DatabaseOperator, bool) {
			operator, ok := operators[id]
			return operator, ok
		},
	}
}
