// Code generated by ggg sync; DO NOT EDIT.
//
// index: 52b40de0b80f039019171eb54f6dab48c73da77dd2d6651c4d54ecbeba16613a
// registry: 9f669c867e59d29d1d37dc7e10bc96447ad705ef66e4f53641a535e7a74194e7

package web

import (
	cspSource0 "github.com/gogogadget/gogogadget/internal/identity/clerk/csp"
)

var CSPSourceProviders = map[string]CSPSourceProvider{
	"identity-clerk-csp": cspSource0.Sources,
}

var CSPDirectiveGrants = map[string][]string{
	"identity-clerk-csp": []string{
		"connect-src",
		"img-src",
		"worker-src",
	},
}

var CSPValueKeys = map[string][]string{
	"identity-clerk-csp": []string{
		"CLERK_FRONTEND_API_URL",
		"CLERK_PORTAL_URL",
		"CLERK_PUBLISHABLE_KEY",
	},
}

var CSPActive = map[string]func(string) bool{
	"identity-clerk-csp": func(env string) bool { return providerActive(env, "ggg/identity", "ggg/system/identity-clerk") },
}
