// Code generated by ggg sync; DO NOT EDIT.
//
// index: 1bfac9fb434a932e7ddeadfa3b485231ecad0e26b5ce5e0c3b566cd53037edaa
// registry: dfa7a8d6681b492f1c335b3e09e030d88a5eaa1acac7ae7f379f3f45f8cdcb99

package web

import (
	cspSource0 "github.com/gogogadget/gogogadget/internal/identity/clerk/csp"
)

var CSPSourceProviders = map[string]CSPSourceProvider{
	"identity-clerk-csp": cspSource0.Sources,
}

var CSPDirectiveGrants = map[string][]string{
	"identity-clerk-csp": []string{
		"connect-src",
		"img-src",
		"worker-src",
	},
}

var CSPValueKeys = map[string][]string{
	"identity-clerk-csp": []string{
		"CLERK_FRONTEND_API_URL",
		"CLERK_PORTAL_URL",
		"CLERK_PUBLISHABLE_KEY",
	},
}

var CSPActive = map[string]func(string) bool{
	"identity-clerk-csp": func(env string) bool { return providerActive(env, "ggg/identity", "ggg/system/identity-clerk") },
}
