// Code generated by ggg sync; DO NOT EDIT.
//
// index: 5e6dd6c43d872cb4e666f1e82e42f6781047e77b5f08f5cc4c270a06bfd550e3
// registry: a0646349b8ca99f57cc7506a5f10c54ba8b638aa148482b7c1baf2b5a41872ba

package content

// ContentRegistry lists selected content types.
var ContentRegistry = []string{
	"post",
	"release",
}
