// Code generated by ggg sync; DO NOT EDIT.
//
// index: fbc0025b71708c0223d22c6740bb4ec89de6a97a178f39fde3a04071c04e71e2
// registry: 4a0a05cf19c323ff94faf4b402435f01d68ef308762b3b097fd6f124ef5bcaa8

package content

// ContentRegistry lists selected content types.
var ContentRegistry = []string{
	"post",
	"release",
}
