// Code generated by ggg sync; DO NOT EDIT.
//
// index: 8f714ee692a5cc6da50fdeeae038beb3958970b6e95a4bb0436c3c2db82af967
// registry: ae377595a5737958b774ccf17a46063e00b87326b38c53d5288aef19bf977cf2

package content

// ContentRegistry lists selected content types.
var ContentRegistry = []string{
	"post",
	"release",
}
