// Code generated by ggg sync; DO NOT EDIT.
//
// index: 52b40de0b80f039019171eb54f6dab48c73da77dd2d6651c4d54ecbeba16613a
// registry: 9f669c867e59d29d1d37dc7e10bc96447ad705ef66e4f53641a535e7a74194e7

package ui

// AlpineFragments are the module-owned Alpine sources, in load order.
var AlpineFragments = []string{
	"/static/ui/engines.js",
	"/static/ui/forms.js",
	"/static/ui/navigation.js",
	"/static/ui/overlays.js",
	"/static/ui/carousel.js",
	"/static/ui/chart.js",
	"/static/ui/markdown-editor.js",
	"/static/ui/panels.js",
	"/static/ui/kanban.js",
	"/static/ui/calendar.js",
	"/static/ui/command.js",
	"/static/ui/tree.js",
	"/static/ui/grid.js",
}
