// Code generated by ggg sync; DO NOT EDIT.
//
// index: 272abf7a2370f784c47a93a651fc5d04414528af609e3917602de52ef8d782fd
// registry: a07cc3f7847b4f9540a6573fc9f4c8fad980313cdfbef0f39bfbc30c47295296

package ui

// AlpineFragments are the module-owned Alpine sources, in load order.
var AlpineFragments = []string{
	"/static/ui/forms.js",
	"/static/ui/navigation.js",
	"/static/ui/overlays.js",
}
