// Code generated by ggg sync; DO NOT EDIT.
//
// index: b1418e1d9d47870a0858404bee688237d4f5f68a18c163118463f67a77ae1fa1
// registry: 3d1f685958575753b57ca3879119c28bfeb1909a1b95068fb25d354c5fc98b28

package ui

// AlpineFragments are the module-owned Alpine sources, in load order.
var AlpineFragments = []string{
	"/static/ui/engines.js",
	"/static/ui/forms.js",
	"/static/ui/navigation.js",
	"/static/ui/overlays.js",
	"/static/ui/carousel.js",
	"/static/ui/chart.js",
	"/static/ui/markdown-editor.js",
	"/static/ui/panels.js",
	"/static/ui/kanban.js",
	"/static/ui/calendar.js",
	"/static/ui/command.js",
	"/static/ui/tree.js",
	"/static/ui/grid.js",
}
