// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// IconButtonOpts configures a button whose only content is an icon.
// Label is required and is not optional by accident: an icon-only button with
// no accessible name is announced as "button" and nothing else, which makes it
// unusable by screen reader and unaddressable by test. The label is applied as
// aria-label and the icon stays decorative, so the name is announced exactly
// once.
type IconButtonOpts struct {
	Icon   IconName
	Label  string
	Type   ButtonType
	Action Action
	Size   Size
	Busy   bool
	// Pressed makes this a toggle: nil is a plain button, a pointer is the
	// current state and renders aria-pressed.
	Pressed  *bool
	Disabled bool
	// HX issues the request the button makes. It is applied after Attrs.HX, so
	// a value set here wins per attribute when both carry the same one.
	HX    HX
	Attrs Attrs
}

// IconButton renders an icon-only control with an accessible name.
func IconButton(o IconButtonOpts) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, withRequest(rootWith("icon-button", buttonClass(o.Action, o.Size)+" btn-icon", o.Attrs,
			"type", string(o.Type.Value()),
			"aria-label", iconButtonLabel(o),
			"aria-busy", boolAttr(o.Busy),
			"aria-pressed", pressedAttr(o.Pressed)), o.HX))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if o.Disabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " disabled")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if o.Busy {
			templ_7745c5c3_Err = Icon(IconOpts{Name: IconSpinner, Attrs: Attrs{Class: iconSizeClass(o.Size) + " animate-spin"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = Icon(IconOpts{Name: o.Icon, Attrs: Attrs{Class: iconSizeClass(o.Size)}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// iconButtonLabel refuses to render a nameless control silently. A missing
// label is a bug in the caller, and a visible placeholder is what gets it
// noticed - an empty aria-label would not.
func iconButtonLabel(o IconButtonOpts) string {
	if o.Label != "" {
		return o.Label
	}
	return "unlabelled " + string(o.Icon) + " button"
}

// pressedAttr renders a toggle's state. A plain button omits aria-pressed
// entirely: claiming a pressed state a control does not have tells a screen
// reader user the button toggles something when it does not.
func pressedAttr(pressed *bool) string {
	if pressed == nil {
		return ""
	}
	if *pressed {
		return "true"
	}
	return "false"
}

var _ = templruntime.GeneratedTemplate
