// Code generated by ggg sync; DO NOT EDIT.
//
// index: 59f5aee2f54273195f63f81673b1265e1b3d4921eebde497e80edeb2f3c3fb12
// registry: 0f7378c35210a85497e58310fdd2097c822840fce5f8b07efb90b9f26a5376f4

package i18n

// catalogESRegistry is the generated es catalog aggregate.
var catalogESRegistry = map[string]string{}
