// Code generated by ggg sync; DO NOT EDIT.
//
// index: cc5226e9cc1f47f6106cf00924230ca85bb9d31647726313ed6bed2e30276a7b
// registry: eaa06e5c59b03cd97838771afaa761fa757002e61374993efff68d484826af41

package jobs

// workerDefinitions assembles every selected job declaration. The table names
// declaration constructors and never knows a payload type, so a module's
// handler stays typed while dispatch stays data.
func workerDefinitions(w *Worker) []Definition {
	return []Definition{
		w.defineEmailDigest(),
		w.defineEmailDunningFinal(),
		w.defineEmailDunningReminder(),
		w.defineEmailPaymentFailed(),
		w.defineEmailSubscriptionCanceled(),
		w.defineEmailTrialEnding(),
		w.defineEmailWelcome(),
		w.defineExportOrgJSON(),
		w.defineExportProjectsCSV(),
		w.defineUsageFlush(),
		w.defineWebhookDeliver(),
	}
}

// SchedulableKinds are the kinds a schedule row may reference. Derived from
// the declarations, so a kind cannot be scheduled unless its module said it
// may be — a schedule pointing at a one-shot handler would fire it forever.
var SchedulableKinds = []string{
	"email.digest",
	"usage.flush",
}

// workerJanitors is every declared cleanup sweep. The pass runs all of them
// and logs per sweep, so one failing sweep cannot strand the rest.
func workerJanitors(w *Worker) []Janitor {
	return []Janitor{
		{Name: "audit_log", Sweep: w.janitorAuditLog},
		{Name: "idempotency_keys", Sweep: w.janitorIdempotencyKeys},
		{Name: "old_jobs", Sweep: w.janitorOldJobs},
		{Name: "webhook_events", Sweep: w.janitorWebhookEvents},
		{Name: "webhook_secrets", Sweep: w.janitorWebhookSecrets},
	}
}

// declaredAttempts is the budget each kind declares. Enqueue helpers write it
// onto the row, and the row is dispatch truth from then on.
var declaredAttempts = map[string]int{
	"email.digest":                8,
	"email.dunning_final":         8,
	"email.dunning_reminder":      8,
	"email.payment_failed":        8,
	"email.subscription_canceled": 8,
	"email.trial_ending":          8,
	"email.welcome":               8,
	"export.org_json":             8,
	"export.projects_csv":         8,
	"usage.flush":                 8,
	"webhook.deliver":             8,
}
