package modkit

import (
	"context"
	"go/format"
	"strings"
	"testing"
)

func genFixtureLock(t *testing.T) (Lock, []Manifest) {
	t.Helper()
	system := Manifest{
		ID: "system/alpha", Kind: ModuleSystem, Name: "alpha",
		Revision: 1, Contract: 1, Title: "Alpha", Description: "Alpha system.",
		Files:         []ManifestFile{},
		Requires:      []string{},
		RemovalPolicy: RemovalFree,
		Runtime: RuntimeContributions{
			System: &SystemContribution{
				Package:     "internal/alpha",
				Constructor: "New",
				Needs: []RuntimeNeed{
					{Field: "Config", Capability: "config", Type: "*config.Config"},
				},
				Provides: []RuntimeProvide{
					{Field: "Alpha", Capability: "alpha", Type: "*alpha.Module"},
				},
				Start: true, Stop: true,
			},
		},
	}
	page := Manifest{
		ID: "page/beta", Kind: ModulePage, Name: "beta",
		Revision: 1, Contract: 1, Title: "Beta", Description: "Beta page.",
		Files:         []ManifestFile{},
		Requires:      []string{"system/alpha"},
		RemovalPolicy: RemovalFree,
		Runtime: RuntimeContributions{
			Routes: []RouteContribution{
				{ID: "beta.show", Method: "GET", Pattern: "/beta", Scope: RoutePublic,
					Policy: RoutePolicy{}, Package: "internal/beta", Handler: "Show"},
			},
		},
	}
	lock := Lock{
		Schema:         1,
		RegistryCommit: testCommitA,
		Order:          []string{"system/alpha", "page/beta"},
		Modules: []LockedModule{
			{ID: "system/alpha", Revision: 1, Contract: 1, SourceCommit: testCommitA, Reason: "explicit",
				RequiredBy: []string{"page/beta"}, Manifest: system, Files: []LockedFile{}, Migrations: []LockedMigration{}},
			{ID: "page/beta", Revision: 1, Contract: 1, SourceCommit: testCommitA, Reason: "explicit",
				RequiredBy: []string{}, Manifest: page, Files: []LockedFile{}, Migrations: []LockedMigration{}},
		},
	}
	return lock, []Manifest{system, page}
}

func TestGenerateAllIsDeterministic(t *testing.T) {
	lock, graph := genFixtureLock(t)
	a, err := GenerateAll(context.Background(), "example.com/acme", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	b, err := GenerateAll(context.Background(), "example.com/acme", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll(second): %v", err)
	}
	if len(a) == 0 {
		t.Fatal("GenerateAll produced no files")
	}
	if len(a) != len(b) {
		t.Fatalf("file counts differ: %d vs %d", len(a), len(b))
	}
	for i := range a {
		if a[i].Path != b[i].Path || a[i].Content != b[i].Content {
			t.Fatalf("file %d differs: %s vs %s", i, a[i].Path, b[i].Path)
		}
	}
}

func TestGeneratedPathsAreToolOwned(t *testing.T) {
	lock, graph := genFixtureLock(t)
	files, err := GenerateAll(context.Background(), "example.com/acme", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	for _, f := range files {
		if !isGeneratedOutput(f.Path) {
			t.Fatalf("generated file %s is not classified as a generated output", f.Path)
		}
	}
}

func TestBootstrapRegistryIsEmitted(t *testing.T) {
	lock, graph := genFixtureLock(t)
	files, err := GenerateAll(context.Background(), "example.com/acme", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	var bootstrap, testhost *GeneratedFile
	for i := range files {
		switch files[i].Path {
		case "internal/modules/bootstrap_registry_gen.go":
			bootstrap = &files[i]
		case "internal/modules/testhost_registry_gen.go":
			testhost = &files[i]
		}
	}
	if bootstrap == nil || testhost == nil {
		t.Fatalf("missing bootstrap/testhost registry files")
	}
	if !strings.Contains(bootstrap.Content, "Code generated by ggg sync; DO NOT EDIT.") {
		t.Fatalf("bootstrap header missing")
	}
	if !strings.Contains(bootstrap.Content, "package modules") {
		t.Fatalf("bootstrap package missing")
	}
	// Deterministic index SHA must be embedded and stable.
	if !strings.Contains(bootstrap.Content, indexSHA(lock)) {
		t.Fatalf("bootstrap does not carry the lock index SHA %s", indexSHA(lock))
	}
}

func TestRoutesRegistryIsEmitted(t *testing.T) {
	lock, graph := genFixtureLock(t)
	files, err := GenerateAll(context.Background(), "example.com/acme", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	var routes *GeneratedFile
	for i := range files {
		if files[i].Path == "internal/web/routes_registry_gen.go" {
			routes = &files[i]
		}
	}
	if routes == nil {
		t.Fatalf("routes_registry_gen.go not generated")
	}
	for _, want := range []string{"package web", "beta.show", "/beta"} {
		if !strings.Contains(routes.Content, want) {
			t.Fatalf("routes registry missing %q", want)
		}
	}
}

func TestIndexSHAChangesWithLock(t *testing.T) {
	lock, graph := genFixtureLock(t)
	first := indexSHA(lock)
	lock.Modules[1].Revision = 2
	second := indexSHA(lock)
	if first == second {
		t.Fatalf("index SHA did not change with lock revision")
	}
	_ = graph
}

// Manifests are distributed to derivatives whose Go module path differs from the
// canonical one, so a manifest must never carry an absolute import path. Package
// fields are module-relative and the generator prefixes the target module path;
// otherwise every installed derivative would import the upstream module and fail
// to compile.
func TestGeneratedImportsUseTargetModulePath(t *testing.T) {
	lock, graph := genFixtureLock(t)
	files, err := GenerateAll(context.Background(), "derivative.example/app", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	var bootstrap string
	for _, file := range files {
		if file.Path == "internal/modules/bootstrap_registry_gen.go" {
			bootstrap = file.Content
		}
	}
	if bootstrap == "" {
		t.Fatal("bootstrap registry was not emitted")
	}
	if want := `"derivative.example/app/internal/alpha"`; !strings.Contains(bootstrap, want) {
		t.Fatalf("bootstrap does not import %s:\n%s", want, bootstrap)
	}
	if strings.Contains(bootstrap, "example.com/acme/internal/alpha") {
		t.Fatalf("bootstrap leaked the canonical module path:\n%s", bootstrap)
	}
}

// Generated Go must parse, must be gofmt-clean, and must not declare unused
// variables. The pipeline runs inside a transaction that has already replaced
// authored files, so emitting source the compiler rejects would leave the tree
// broken until someone hand-edited a DO-NOT-EDIT file.
func TestGeneratedGoIsParseableAndFormatted(t *testing.T) {
	lock, graph := genFixtureLock(t)
	files, err := GenerateAll(context.Background(), "derivative.example/app", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	emitted := 0
	for _, file := range files {
		if !strings.HasSuffix(file.Path, ".go") {
			continue
		}
		emitted++
		formatted, err := format.Source([]byte(file.Content))
		if err != nil {
			t.Fatalf("%s does not parse: %v\n%s", file.Path, err, file.Content)
		}
		if string(formatted) != file.Content {
			t.Fatalf("%s is not gofmt-clean:\n--- emitted ---\n%s\n--- gofmt ---\n%s",
				file.Path, file.Content, formatted)
		}
	}
	if emitted == 0 {
		t.Fatal("no Go files were emitted")
	}
}

// Every capability a module provides must be reachable from the booted runtime.
// A constructor whose result is dropped is both dead wiring and a compile error.
func TestBootstrapExposesProvidedCapabilities(t *testing.T) {
	lock, graph := genFixtureLock(t)
	files, err := GenerateAll(context.Background(), "derivative.example/app", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	var bootstrap string
	for _, file := range files {
		if file.Path == "internal/modules/bootstrap_registry_gen.go" {
			bootstrap = file.Content
		}
	}
	for _, m := range graph {
		if m.Runtime.System == nil {
			continue
		}
		for _, provide := range m.Runtime.System.Provides {
			field := capabilityField(provide.Capability)
			if !strings.Contains(bootstrap, "\t"+field+" ") {
				t.Fatalf("runtime has no field for capability %q (want %q):\n%s",
					provide.Capability, field, bootstrap)
			}
			if !strings.Contains(bootstrap, "r."+field+" = ") {
				t.Fatalf("capability %q is never assigned to the runtime:\n%s",
					provide.Capability, bootstrap)
			}
		}
	}
}

// An emitter must not render a table for a contribution kind nothing declares.
// The generated file would reference a type the project has no reason to define,
// turning an unused feature into a build break — and generated files are
// DO-NOT-EDIT, so the operator has no legitimate way to fix it.
func TestEmittersSkipUndeclaredContributionKinds(t *testing.T) {
	lock, graph := genFixtureLock(t)
	for i := range graph {
		graph[i].Runtime.Jobs = nil
		graph[i].Runtime.Routes = nil
		graph[i].Runtime.ContentTypes = nil
	}
	for i := range lock.Modules {
		lock.Modules[i].Manifest.Runtime.Jobs = nil
		lock.Modules[i].Manifest.Runtime.Routes = nil
		lock.Modules[i].Manifest.Runtime.ContentTypes = nil
	}

	files, err := GenerateAll(context.Background(), "example.com/acme", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	for _, file := range files {
		for _, forbidden := range []string{"jobs_registry_gen", "routes_registry_gen"} {
			if strings.Contains(file.Path, forbidden) {
				t.Fatalf("emitted %s with no matching contributions:\n%s", forbidden, file.Content)
			}
		}
	}
}

// A module that declares stop must actually be stopped, in reverse dependency
// order. A generated Close that discards its stoppers leaks pools and
// connections on every shutdown while looking correct.
func TestBootstrapClosesStoppableModulesInReverseOrder(t *testing.T) {
	lock, graph := genFixtureLock(t)
	// Give the fixture a second stoppable module so order is observable.
	second := Manifest{
		ID: "system/omega", Kind: ModuleSystem, Name: "omega",
		Revision: 1, Contract: 1, Title: "Omega", Description: "Omega system.",
		Files: []ManifestFile{}, Requires: []string{"system/alpha"}, RemovalPolicy: RemovalFree,
		Runtime: RuntimeContributions{System: &SystemContribution{
			Package: "internal/omega", Constructor: "NewModule",
			Needs:    []RuntimeNeed{{Field: "Alpha", Capability: "alpha", Type: "*alpha.Module"}},
			Provides: []RuntimeProvide{{Field: "Omega", Capability: "omega", Type: "*omega.Module"}},
			Stop:     true,
		}},
	}
	graph = append(graph, second)
	lock.Order = append(lock.Order, "system/omega")
	lock.Modules = append(lock.Modules, LockedModule{
		ID: "system/omega", Revision: 1, Contract: 1, SourceCommit: testCommitA,
		Reason: "explicit", RequiredBy: []string{}, Manifest: second,
		Files: []LockedFile{}, Migrations: []LockedMigration{},
	})

	files, err := GenerateAll(context.Background(), "derivative.example/app", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	var bootstrap string
	for _, file := range files {
		if file.Path == "internal/modules/bootstrap_registry_gen.go" {
			bootstrap = file.Content
		}
	}
	if strings.Contains(bootstrap, "_ = system_") {
		t.Fatalf("Close discards its stoppers instead of calling them:\n%s", bootstrap)
	}

	// Stop hooks are registered during Boot, so dependency order is captured by
	// append order; Close then walks the slice backwards.
	bootBody := bootstrap[strings.Index(bootstrap, "func Boot("):strings.Index(bootstrap, "func (r *Runtime) Handler(")]
	alpha := strings.Index(bootBody, "r.stop = append(r.stop, system_alphaModule.Stop)")
	omega := strings.Index(bootBody, "r.stop = append(r.stop, system_omegaModule.Stop)")
	if alpha < 0 || omega < 0 {
		t.Fatalf("Boot does not register both stop hooks:\n%s", bootBody)
	}
	if alpha > omega {
		t.Fatalf("stop hooks registered out of dependency order:\n%s", bootBody)
	}

	closeBody := bootstrap[strings.Index(bootstrap, "func (r *Runtime) Close("):]
	if !strings.Contains(closeBody, "for i := len(r.stop) - 1; i >= 0; i--") {
		t.Fatalf("Close does not stop in reverse order:\n%s", closeBody)
	}
	if !strings.Contains(closeBody, "errors.Join(errs...)") {
		t.Fatalf("Close abandons later stop hooks after a failure:\n%s", closeBody)
	}
}

// A provided type can come from a package the providing module merely uses —
// a pool, a generated query struct. The bootstrap imports module packages, so
// without declared type imports the generated Runtime references undefined
// identifiers and the whole project stops compiling.
func TestBootstrapImportsDeclaredProvideTypePackages(t *testing.T) {
	lock, graph := genFixtureLock(t)
	for i := range graph {
		if graph[i].Runtime.System == nil {
			continue
		}
		graph[i].Runtime.System.TypeImports = []string{
			"github.com/jackc/pgx/v5/pgxpool",
			"internal/db/sqlc",
		}
		graph[i].Runtime.System.Provides = []RuntimeProvide{
			{Field: "Pool", Capability: "database.pool", Type: "*pgxpool.Pool"},
			{Field: "Queries", Capability: "database.queries", Type: "*sqlc.Queries"},
		}
	}
	for i := range lock.Modules {
		lock.Modules[i].Manifest = graph[i]
	}

	files, err := GenerateAll(context.Background(), "derivative.example/app", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	var bootstrap string
	for _, file := range files {
		if file.Path == "internal/modules/bootstrap_registry_gen.go" {
			bootstrap = file.Content
		}
	}
	// An external module path is used verbatim; a module-relative one is
	// qualified against the target module, exactly like a system package.
	for _, want := range []string{
		`"github.com/jackc/pgx/v5/pgxpool"`,
		`"derivative.example/app/internal/db/sqlc"`,
	} {
		if !strings.Contains(bootstrap, want) {
			t.Fatalf("bootstrap does not import %s:\n%s", want, bootstrap)
		}
	}
}

// A module that declares start owns a long-lived service. The generated Run must
// actually start it: a Run that returns nil without starting anything means the
// job worker never claims a row while every test still passes.
func TestBootstrapRunsStartableModules(t *testing.T) {
	lock, graph := genFixtureLock(t)
	for i := range graph {
		if graph[i].Runtime.System != nil {
			graph[i].Runtime.System.Start = true
		}
	}
	for i := range lock.Modules {
		lock.Modules[i].Manifest = graph[i]
	}

	files, err := GenerateAll(context.Background(), "derivative.example/app", lock, graph)
	if err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}
	var bootstrap string
	for _, file := range files {
		if file.Path == "internal/modules/bootstrap_registry_gen.go" {
			bootstrap = file.Content
		}
	}
	if !strings.Contains(bootstrap, "r.start = append(r.start, system_alphaModule.Start)") {
		t.Fatalf("Boot does not register the start hook:\n%s", bootstrap)
	}
	runBody := bootstrap[strings.Index(bootstrap, "func (r *Runtime) Run("):]
	runBody = runBody[:strings.Index(runBody, "\n}\n")]
	if !strings.Contains(runBody, "for _, start := range r.start") {
		t.Fatalf("Run does not start registered services:\n%s", runBody)
	}
	if !strings.Contains(runBody, "return err") {
		t.Fatalf("Run swallows a start failure:\n%s", runBody)
	}
}
