// Code generated by ggg sync; DO NOT EDIT.
//
// index: b550b1b8b2a8f6ae47112152d290f83370ff46e7151076223988aa535be8ce50
// registry: 87c831edadfce4e913b2f789ce2b2e3c3c8c030f28cc5a5201647ed5139706e5

package modules

import (
	"context"
	"fmt"
	"net/http"

	analytics "github.com/gogogadget/gogogadget/internal/analytics"
	apphost "github.com/gogogadget/gogogadget/internal/apphost"
	billing "github.com/gogogadget/gogogadget/internal/billing"
	config "github.com/gogogadget/gogogadget/internal/config"
	identity "github.com/gogogadget/gogogadget/internal/identity"
	llm "github.com/gogogadget/gogogadget/internal/llm"
	mail "github.com/gogogadget/gogogadget/internal/mail"
	observability "github.com/gogogadget/gogogadget/internal/observability"
	storage "github.com/gogogadget/gogogadget/internal/storage"
)

// Options carries the ambient values the selected closure boots with.
type Options struct {
}

// Runtime is the booted module closure. Every capability the selected
// graph provides is reachable here, so consumers take typed values rather
// than reconstructing providers.
type Runtime struct {
	handler http.Handler
	stop    []apphost.Stop

	AnalyticsCapturer     analytics.Capturer
	BillingClient         billing.Client
	Config                *config.Config
	IdentityDeleter       identity.Deleter
	IdentityFetcher       identity.UserFetcher
	IdentityVerifier      identity.Verifier
	LlmCompleter          llm.Completer
	MailSender            mail.Sender
	ObservabilityReporter observability.Reporter
	StorageStore          storage.Store
}

// Boot validates the selected closure and constructs typed dependencies in
// stable topological order, then starts long-lived services.
func Boot(ctx context.Context, h apphost.Host, opts Options) (*Runtime, error) {
	r := &Runtime{}
	_ = h
	system_configModule, err := config.NewModule(ctx, h, config.Deps{})
	if err != nil {
		return nil, fmt.Errorf("boot system/config: %w", err)
	}
	r.Config = system_configModule.Config
	system_analyticsModule, err := analytics.NewModule(ctx, h, analytics.Deps{
		Config: r.Config,
	})
	if err != nil {
		return nil, fmt.Errorf("boot system/analytics: %w", err)
	}
	r.AnalyticsCapturer = system_analyticsModule.Capturer
	system_billingModule, err := billing.NewModule(ctx, h, billing.Deps{
		Config: r.Config,
	})
	if err != nil {
		return nil, fmt.Errorf("boot system/billing: %w", err)
	}
	r.BillingClient = system_billingModule.Client
	system_identityModule, err := identity.NewModule(ctx, h, identity.Deps{
		Config: r.Config,
	})
	if err != nil {
		return nil, fmt.Errorf("boot system/identity: %w", err)
	}
	r.IdentityDeleter = system_identityModule.Deleter
	r.IdentityFetcher = system_identityModule.Fetcher
	r.IdentityVerifier = system_identityModule.Verifier
	system_llmModule, err := llm.NewModule(ctx, h, llm.Deps{
		Config: r.Config,
	})
	if err != nil {
		return nil, fmt.Errorf("boot system/llm: %w", err)
	}
	r.LlmCompleter = system_llmModule.Completer
	system_mailModule, err := mail.NewModule(ctx, h, mail.Deps{
		Config: r.Config,
	})
	if err != nil {
		return nil, fmt.Errorf("boot system/mail: %w", err)
	}
	r.MailSender = system_mailModule.Sender
	system_observabilityModule, err := observability.NewModule(ctx, h, observability.Deps{
		Config: r.Config,
	})
	if err != nil {
		return nil, fmt.Errorf("boot system/observability: %w", err)
	}
	r.ObservabilityReporter = system_observabilityModule.Reporter
	system_storageModule, err := storage.NewModule(ctx, h, storage.Deps{
		Config: r.Config,
	})
	if err != nil {
		return nil, fmt.Errorf("boot system/storage: %w", err)
	}
	r.StorageStore = system_storageModule.Store
	return r, nil
}

// Handler returns the composed HTTP handler.
func (r *Runtime) Handler() http.Handler { return r.handler }

// Run starts long-lived services.
func (r *Runtime) Run(ctx context.Context) error { return nil }

// Close stops services in reverse dependency order.
func (r *Runtime) Close(ctx context.Context) error {
	return nil
}
