// Code generated by ggg sync; DO NOT EDIT.
//
// index: 17fd824f627f1d258a9b169b7834a8f1e11e66003282cfc5bdfec4248a680d7e
// registry: 5a63e58c161140f20f0532be634277bc8ba1cdf577363fc178dff63fd4652e5f

package db

// DataLifecycle is one declared data obligation: the delete behaviour the
// schema is expected to provide and whether the rows are exportable.
type DataLifecycle struct {
	Table              string
	Module             string
	Scope              string
	Export             bool
	AccountDelete      string
	OrganizationDelete string
}

// DataLifecycleRegistry lists every declared table in module order. Export
// collectors and deletion paths are checked against this list, so a module
// that declares data cannot be omitted from either silently.
var DataLifecycleRegistry = []DataLifecycle{
	{Table: "announcements", Module: "system/announcements", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "org_members", Module: "system/organizations", Scope: "org", Export: true, AccountDelete: "cascade", OrganizationDelete: "cascade"},
	{Table: "orgs", Module: "system/organizations", Scope: "org", Export: true, AccountDelete: "manual", OrganizationDelete: "manual"},
	{Table: "users", Module: "system/organizations", Scope: "user", Export: true, AccountDelete: "manual", OrganizationDelete: "retain"},
	{Table: "audit_log", Module: "system/audit", Scope: "org", Export: true, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "subscriptions", Module: "system/billing", Scope: "org", Export: true, AccountDelete: "retain", OrganizationDelete: "cascade"},
	{Table: "content_entries", Module: "system/content", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "content_media", Module: "system/content", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "content_revisions", Module: "system/content", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "feature_flags", Module: "system/feature-flags", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "flag_overrides", Module: "system/feature-flags", Scope: "org", Export: false, AccountDelete: "retain", OrganizationDelete: "cascade"},
	{Table: "impersonation_sessions", Module: "system/impersonation", Scope: "user", Export: false, AccountDelete: "manual", OrganizationDelete: "retain"},
	{Table: "notification_preferences", Module: "system/notifications", Scope: "user", Export: true, AccountDelete: "cascade", OrganizationDelete: "retain"},
	{Table: "notifications", Module: "system/notifications", Scope: "user", Export: true, AccountDelete: "cascade", OrganizationDelete: "cascade"},
	{Table: "api_tokens", Module: "system/api", Scope: "org", Export: true, AccountDelete: "retain", OrganizationDelete: "cascade"},
	{Table: "idempotency_keys", Module: "system/api", Scope: "org", Export: false, AccountDelete: "retain", OrganizationDelete: "cascade"},
	{Table: "schedules", Module: "system/schedules", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "jobs", Module: "system/jobs", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "usage_events", Module: "system/usage", Scope: "org", Export: true, AccountDelete: "retain", OrganizationDelete: "cascade"},
	{Table: "webhook_deliveries", Module: "system/webhooks", Scope: "org", Export: false, AccountDelete: "retain", OrganizationDelete: "cascade"},
	{Table: "webhook_endpoints", Module: "system/webhooks", Scope: "org", Export: true, AccountDelete: "retain", OrganizationDelete: "cascade"},
	{Table: "webhook_events", Module: "system/webhooks", Scope: "platform", Export: false, AccountDelete: "retain", OrganizationDelete: "retain"},
	{Table: "files", Module: "workflow/files", Scope: "org", Export: true, AccountDelete: "cascade", OrganizationDelete: "cascade"},
	{Table: "projects", Module: "workflow/projects", Scope: "org", Export: true, AccountDelete: "cascade", OrganizationDelete: "cascade"},
}
