// Code generated by ggg sync; DO NOT EDIT.
//
// index: 0387c0996f7c8a69d8b9daae14a79447efac97daa15a9f72bf58fad2b934063b
// registry: 45f6b0433de61b6da58f5687469e0f43d3742eed71429f14434f646f6a9a32ac

package db

// SeedFragments lists seed fragments per fixture set, in module order. The
// loader executes them in this order; fragments are idempotent so the set is
// re-runnable. Order is the lock's dependency order, so a fragment never
// loads before the rows it references.
// PersonaRecords mirrors the generated e2e personas in Go, so the
// fixture-parity check reads the same declaration the specs do.
var PersonaRecords = []struct{ ID, User, Org, Role string }{
	{ID: "free", User: "user_free", Org: "org_free", Role: "org:member"},
	{ID: "pro", User: "user_pro", Org: "org_pro", Role: "org:admin"},
	{ID: "admin", User: "user_admin", Org: "org_free", Role: "org:admin"},
	{ID: "support", User: "user_support", Org: "org_free", Role: "org:admin"},
	{ID: "disabled", User: "user_disabled", Org: "org_free", Role: "org:member"},
	{ID: "noorg", User: "user_noorg", Org: "", Role: ""},
	{ID: "noactive", User: "user_noactive", Org: "", Role: ""},
	{ID: "toggle", User: "user_toggle", Org: "org_free", Role: "org:member"},
	{ID: "deleteme", User: "user_deleteme", Org: "org_deleteme", Role: "org:admin"},
}

var SeedFragments = map[string][]string{
	"dev": {
		"internal/db/testdata/seed/dev/announcements.sql",
		"internal/db/testdata/seed/dev/organizations.sql",
		"internal/db/testdata/seed/dev/flags.sql",
		"internal/db/testdata/seed/dev/notifications.sql",
		"internal/db/testdata/seed/dev/schedules.sql",
		"internal/db/testdata/seed/dev/projects.sql",
	},
	"e2e": {
		"internal/db/testdata/seed/e2e/organizations.sql",
		"internal/db/testdata/seed/e2e/audit.sql",
		"internal/db/testdata/seed/e2e/billing.sql",
		"internal/db/testdata/seed/e2e/flags.sql",
		"internal/db/testdata/seed/e2e/notifications.sql",
		"internal/db/testdata/seed/e2e/projects.sql",
	},
}
