// Code generated by ggg sync; DO NOT EDIT.
//
// index: f49ba02565c7b3c96e3c38edb31880d9e71742ad54140968537320e2c9637626
// registry: 94fa0e0440ef26c1d4067042b2697937973f6b342d9613edf4166897a8c6aade

package db

// SeedFragments lists seed fragments per fixture set, in module order. The
// loader executes them in this order; fragments are idempotent so the set is
// re-runnable. Order is the lock's dependency order, so a fragment never
// loads before the rows it references.
// PersonaRecords mirrors the generated e2e personas in Go, so the
// fixture-parity check reads the same declaration the specs do.
var PersonaRecords = []struct{ ID, User, Org, Role string }{
	{ID: "free", User: "user_free", Org: "org_free", Role: "org:member"},
	{ID: "pro", User: "user_pro", Org: "org_pro", Role: "org:admin"},
	{ID: "admin", User: "user_admin", Org: "org_free", Role: "org:admin"},
	{ID: "support", User: "user_support", Org: "org_free", Role: "org:admin"},
	{ID: "disabled", User: "user_disabled", Org: "org_free", Role: "org:member"},
	{ID: "noorg", User: "user_noorg", Org: "", Role: ""},
	{ID: "noactive", User: "user_noactive", Org: "", Role: ""},
	{ID: "toggle", User: "user_toggle", Org: "org_free", Role: "org:member"},
	{ID: "deleteme", User: "user_deleteme", Org: "org_deleteme", Role: "org:admin"},
}

var SeedFragments = map[string][]string{
	"dev": {
		"internal/db/testdata/seed/dev/announcements.sql",
		"internal/db/testdata/seed/dev/organizations.sql",
		"internal/db/testdata/seed/dev/flags.sql",
		"internal/db/testdata/seed/dev/notifications.sql",
		"internal/db/testdata/seed/dev/schedules.sql",
		"internal/db/testdata/seed/dev/projects.sql",
	},
	"e2e": {
		"internal/db/testdata/seed/e2e/organizations.sql",
		"internal/db/testdata/seed/e2e/audit.sql",
		"internal/db/testdata/seed/e2e/billing.sql",
		"internal/db/testdata/seed/e2e/flags.sql",
		"internal/db/testdata/seed/e2e/notifications.sql",
		"internal/db/testdata/seed/e2e/projects.sql",
	},
}
