// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/gogogadget/gogogadget/internal/web/templates/ui"

// The dashboard scenario: the surface a signed-in user lands on.
//
// Everything below is literal fixture data declared in this file. A dev surface
// that reads the database renders differently on every machine, which makes a
// visual baseline useless and a reported difference unfalsifiable.

// ScenarioDashboard renders the app landing surface.
//
// The four regions - controls, onboarding, headline numbers, activity - are
// emitted in the same order and the same containers in every state. That is the
// whole point of the loading state: skeletons stand where the real content will
// land, so arriving data does not move the button the user was about to press.
func ScenarioDashboard(gc GalleryContext) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\" data-testid=\"scenario-dashboard\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = ui.CommandPalette(dashboardCommandPalette()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.ButtonLink(ui.ButtonLinkOpts{
				Label: "New project", Href: "/dev/scenarios/resource-list",
				Action: ui.ActionPrimary, Size: ui.SizeSM, Icon: ui.IconAdd,
				Attrs: ui.Attrs{TestID: "dashboard-new-project"},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = ui.Toolbar(ui.ToolbarOpts{Label: "Dashboard controls", Attrs: ui.Attrs{TestID: "dashboard-controls"}}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if gc.State == "loading" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "   ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonOpts{Lines: 5}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = ui.Card(ui.CardOpts{Attrs: ui.Attrs{TestID: "dashboard-onboarding-loading"}}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = ui.OnboardingChecklist(dashboardChecklist(gc)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			if gc.State == "loading" {
				for _, slot := range dashboardMetricSlots() {
					templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
						templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
						if !templ_7745c5c3_IsBuffer {
							defer func() {
								templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err == nil {
									templ_7745c5c3_Err = templ_7745c5c3_BufErr
								}
							}()
						}
						ctx = templ.InitializeContext(ctx)
						templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonOpts{Lines: 2}).Render(ctx, templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						return nil
					})
					templ_7745c5c3_Err = ui.Card(ui.CardOpts{Attrs: ui.Attrs{TestID: slot}}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else {
				for _, metric := range dashboardMetrics(gc) {
					templ_7745c5c3_Err = ui.Metric(metric).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			return nil
		})
		templ_7745c5c3_Err = ui.StatGroup(ui.StatGroupOpts{
			Label: "Workspace totals", Columns: 3,
			Attrs: ui.Attrs{TestID: "dashboard-stats"},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if gc.State == "empty" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "   ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.EmptyState(ui.EmptyStateOpts{
				Title: "No numbers yet",
				// Directly under the page title with no region heading between,
				// so h2. The activity empty state below sits inside a titled
				// section and keeps its default h3.
				Level: 2,
				Body:  dashboardText(gc.LongContent, "These totals count projects, runs and storage across the workspace. The first project you create starts them.", "These totals count projects, runs and storage across every member of the workspace, including the ones shared with you by other organisations you belong to. They stay at zero until the first project is created, and the first run of that project is what starts the weekly counters moving."),
				Attrs: ui.Attrs{TestID: "dashboard-stats-empty"},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			switch gc.State {
			case "loading":
				templ_7745c5c3_Var7 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = ui.Skeleton(ui.SkeletonOpts{Lines: 4}).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = ui.Card(ui.CardOpts{Attrs: ui.Attrs{TestID: "dashboard-activity-loading"}}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case "empty":
				templ_7745c5c3_Err = ui.EmptyState(ui.EmptyStateOpts{
					Title: "Nothing has happened yet",
					Body:  "Every create, invite and token rotation in this workspace appears here.",
					Attrs: ui.Attrs{TestID: "dashboard-activity-empty"},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			default:
				templ_7745c5c3_Var8 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Var9 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
						templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
						if !templ_7745c5c3_IsBuffer {
							defer func() {
								templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err == nil {
									templ_7745c5c3_Err = templ_7745c5c3_BufErr
								}
							}()
						}
						ctx = templ.InitializeContext(ctx)
						for _, entry := range dashboardActivity(gc) {
							templ_7745c5c3_Err = ui.ActivityItem(entry).Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return templ_7745c5c3_Err
							}
						}
						return nil
					})
					templ_7745c5c3_Err = ui.List(ui.ListOpts{Attrs: ui.Attrs{TestID: "dashboard-activity-list"}}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var9), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = ui.Card(ui.CardOpts{}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var8), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return nil
		})
		templ_7745c5c3_Err = ui.Section(ui.SectionOpts{
			Title: "Recent activity", Level: 2,
			Attrs: ui.Attrs{ID: "dashboard-activity", TestID: "dashboard-activity"},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// dashboardCommandPalette wires the palette to destinations that exist.
// SearchURL is deliberately empty. The scenario owns no fragment endpoint of
// its own, and pointing the palette at another surface's fragment route would
// swap that surface's markup into these results - a control that looks wired
// and answers with the wrong thing. Without it the palette is exactly what it
// degrades to with no scripting: a search form that submits to a real page.
func dashboardCommandPalette() ui.CommandPaletteOpts {
	return ui.CommandPaletteOpts{
		ID:          "dashboard-command",
		Label:       "Search commands",
		FallbackURL: "/dev/gallery",
		Target:      ui.NavTarget,
		Attrs:       ui.Attrs{TestID: "dashboard-command"},
		Groups: []ui.CommandGroupData{
			{Title: "Go to", Items: []ui.CommandItemData{
				{ID: "cmd-projects", Label: "Projects", Href: "/dev/scenarios/resource-list", Icon: ui.IconFolder, Hint: "Workspace"},
				{ID: "cmd-settings", Label: "Settings", Href: "/dev/scenarios/settings", Icon: ui.IconSettings, Hint: "Workspace"},
				{ID: "cmd-team", Label: "Team", Href: "/dev/scenarios/team", Icon: ui.IconTeam, Hint: "Workspace"},
			}},
			{Title: "Reference", Items: []ui.CommandItemData{
				{ID: "cmd-components", Label: "Component catalog", Href: "/dev/gallery", Icon: ui.IconChart},
				{ID: "cmd-forms", Label: "Form components", Href: "/dev/gallery/forms", Icon: ui.IconEdit},
			}},
		},
	}
}

// dashboardChecklist is the setup list at two points in a workspace's life.
//
// The empty case is the same four steps with none complete rather than a
// shorter list: a checklist that grows as you finish it never shows how much is
// left, which is the only question a first-run user is asking.
func dashboardChecklist(gc GalleryContext) ui.OnboardingChecklistOpts {
	steps := []ui.ChecklistStep{
		{
			Label: "Create the workspace", Href: "/dev/scenarios/settings",
			Body:      dashboardText(gc.LongContent, "Name it and pick a region.", "Name it, pick the region its data is stored in, and decide whether members join by invitation only or by verified email domain."),
			Done:      true,
			DoneLabel: "completed 12 Jan 2026",
		},
		{
			Label: "Invite a teammate", Href: "/dev/scenarios/team",
			Body:      "Owners can invite by email or share a join link.",
			Done:      true,
			DoneLabel: "completed 13 Jan 2026",
		},
		{
			Label: "Create your first project", Href: "/dev/scenarios/resource-list",
			Body: dashboardText(gc.LongContent, "A project holds runs, files and its own API tokens.", "A project holds its runs, its uploaded files and its own scoped API tokens, so revoking access to one project never affects the others in the workspace."),
		},
		{
			Label: "Add a billing method", Href: "/dev/scenarios/billing",
			Body: "The free plan covers 10 GB and 5,000 runs a month.",
		},
	}
	if gc.State == "empty" {
		// Brand-new org: nothing is done, so step one is the only live target.
		for i := range steps {
			steps[i].Done = false
			steps[i].DoneLabel = ""
		}
	}
	return ui.OnboardingChecklistOpts{
		Title:         "Finish setting up",
		ProgressLabel: "Workspace setup progress",
		// First heading on the surface, directly under the page title.
		Level: 2,
		Steps: steps,
		Attrs: ui.Attrs{TestID: "dashboard-onboarding"},
	}
}

// dashboardMetricSlots names the loading placeholders so the skeleton count and
// the metric count cannot drift apart: three cards either way, so the grid is
// the same shape before and after the data arrives.
func dashboardMetricSlots() []string {
	return []string{"dashboard-stat-projects", "dashboard-stat-runs", "dashboard-stat-storage"}
}

func dashboardMetrics(gc GalleryContext) []ui.MetricOpts {
	if gc.State == "empty" {
		return []ui.MetricOpts{
			{Title: "Active projects", Value: "0", Sub: "None created yet", Attrs: ui.Attrs{TestID: "dashboard-stat-projects"}},
			{Title: "Runs this week", Value: "0", Sub: "No runs recorded", Attrs: ui.Attrs{TestID: "dashboard-stat-runs"}},
			{Title: "Storage used", Value: "0 GB", Sub: "of 10 GB included", Attrs: ui.Attrs{TestID: "dashboard-stat-storage"}},
		}
	}
	return []ui.MetricOpts{
		{
			Title: dashboardText(gc.LongContent, "Active projects", "Active projects across every organisation you belong to"),
			Value: "12", Sub: "2 created since 08 Jan 2026",
			Attrs: ui.Attrs{TestID: "dashboard-stat-projects"},
		},
		{
			Title: "Runs this week",
			Value: "1,204", Sub: "94% succeeded",
			Attrs: ui.Attrs{TestID: "dashboard-stat-runs"},
		},
		{
			Title: "Storage used",
			Value: "3.2 GB", Sub: "of 10 GB included",
			Attrs: ui.Attrs{TestID: "dashboard-stat-storage"},
		},
	}
}

// dashboardActivity is a fixed audit tail. The timestamps are literal strings
// rather than a formatted clock reading, so two renders are byte-identical and
// a visual difference means the markup changed.
func dashboardActivity(gc GalleryContext) []ui.ActivityItemOpts {
	return []ui.ActivityItemOpts{
		{
			Actor: "Ada Lovelace", Action: "created", Target: "Apollo",
			Timestamp: "15 Jan 2026, 09:12", MachineTime: "2026-01-15T09:12:00Z", Icon: ui.IconAdd,
		},
		{
			Actor: "Grace Hopper", Action: "invited", Target: dashboardText(gc.LongContent, "marta@example.com", "marta.rodriguez.de.la.fuente@a-deliberately-long-tenant-domain.example.com"),
			Timestamp: "14 Jan 2026, 17:40", MachineTime: "2026-01-14T17:40:00Z", Icon: ui.IconTeam,
		},
		{
			Actor: "Ada Lovelace", Action: "rotated the deploy token of", Target: "Apollo",
			Timestamp: "14 Jan 2026, 11:05", MachineTime: "2026-01-14T11:05:00Z", Icon: ui.IconKey,
		},
		{
			Actor: "Grace Hopper", Action: "archived", Target: "Borealis",
			Timestamp: "13 Jan 2026, 08:58", MachineTime: "2026-01-13T08:58:00Z", Icon: ui.IconFolder,
		},
	}
}

// dashboardText picks the long variant when the reader asked to stress layout.
// The long string is a real sentence rather than repeated filler: filler wraps
// evenly and hides exactly the overflow a long proper noun causes.
func dashboardText(long bool, short, extended string) string {
	if long {
		return extended
	}
	return short
}

var _ = templruntime.GeneratedTemplate
