// Code generated by ggg sync; DO NOT EDIT.
//
// index: 1e9f957d1e1d0ef906a836cad664f33aba5763ecf4bfac23941f34ab113cae8a
// registry: aff757f4c0c2d9499aae5d8ff1f3026a0c8f28d153437630af8d57299a00d666

package templates

// SettingsTab is one settings tab and the conditions under which it is shown.
type SettingsTab struct {
	Item  NavItem
	Roles []string
	Flags []string
}

// SettingsNavigationRegistry is the declared settings tabs in order. Use
// settingsTabs(ctx) to get the subset the current viewer may see.
var SettingsNavigationRegistry = []SettingsTab{
	{Item: NavItem{ID: "nav.settings.account", LabelKey: "settings.tab_account", Href: "/app/settings/account"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.org", LabelKey: "settings.tab_org", Href: "/app/settings/org"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.billing", LabelKey: "settings.tab_billing", Href: "/app/settings/billing"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.api", LabelKey: "settings.tab_api", Href: "/app/settings/api"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.webhooks", LabelKey: "settings.tab_webhooks", Href: "/app/settings/webhooks"}, Roles: nil, Flags: []string{"webhooks"}},
	{Item: NavItem{ID: "nav.settings.notifications", LabelKey: "settings.tab_notifications", Href: "/app/settings/notifications"}, Roles: nil, Flags: nil},
}
