// Code generated by ggg sync; DO NOT EDIT.
//
// index: b82211d0914e5765673b6784d71525970ee45ffcd85f5e7e9f5c448e31f13b65
// registry: 5221aaf8a98db6a9874aa76bc6fd74fc1cabd345cdf173599802a1bbd26674b1

package templates

// SettingsTab is one settings tab and the conditions under which it is shown.
type SettingsTab struct {
	Item  NavItem
	Roles []string
	Flags []string
}

// SettingsNavigationRegistry is the declared settings tabs in order. Use
// settingsTabs(ctx) to get the subset the current viewer may see.
var SettingsNavigationRegistry = []SettingsTab{
	{Item: NavItem{ID: "nav.settings.account", LabelKey: "settings.tab_account", Href: "/app/settings/account"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.org", LabelKey: "settings.tab_org", Href: "/app/settings/org"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.billing", LabelKey: "settings.tab_billing", Href: "/app/settings/billing"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.api", LabelKey: "settings.tab_api", Href: "/app/settings/api"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.webhooks", LabelKey: "settings.tab_webhooks", Href: "/app/settings/webhooks"}, Roles: nil, Flags: []string{"webhooks"}},
	{Item: NavItem{ID: "nav.settings.notifications", LabelKey: "settings.tab_notifications", Href: "/app/settings/notifications"}, Roles: nil, Flags: nil},
}
