// Code generated by ggg sync; DO NOT EDIT.
//
// index: a6caf0d8e1845cd95353622fd238160f83137884ad4e0a6348edcde50084d485
// registry: db43deadce4f68063f78ff07577126b7fa270c3117a05a7a782a30f42d0421c6

package templates

// SettingsTab is one settings tab and the conditions under which it is shown.
type SettingsTab struct {
	Item  NavItem
	Roles []string
	Flags []string
}

// SettingsNavigationRegistry is the declared settings tabs in order. Use
// settingsTabs(ctx) to get the subset the current viewer may see.
var SettingsNavigationRegistry = []SettingsTab{
	{Item: NavItem{ID: "nav.settings.account", LabelKey: "settings.tab_account", Href: "/app/settings/account"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.org", LabelKey: "settings.tab_org", Href: "/app/settings/org"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.billing", LabelKey: "settings.tab_billing", Href: "/app/settings/billing"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.api", LabelKey: "settings.tab_api", Href: "/app/settings/api"}, Roles: nil, Flags: nil},
	{Item: NavItem{ID: "nav.settings.webhooks", LabelKey: "settings.tab_webhooks", Href: "/app/settings/webhooks"}, Roles: nil, Flags: []string{"webhooks"}},
	{Item: NavItem{ID: "nav.settings.notifications", LabelKey: "settings.tab_notifications", Href: "/app/settings/notifications"}, Roles: nil, Flags: nil},
}
