// Code generated by ggg sync; DO NOT EDIT.
//
// index: 292abd19d1f1f4181ca5f71c394cbb2ed535b55422b0da0cb04bb012058b3c43
// registry: ae02e1628a1961275a4c33a8dd3071c4b93c1f334ef69e0a0ad9cb46e87675c2

package templates

var ShellSlotsRegistry = map[string][]string{}

var ShellSlotRenderers = map[string]any{}

var ShellSlotActive = map[string]func(string) bool{}
