// Code generated by ggg sync; DO NOT EDIT.
//
// index: abb702a789688302153ab069cc3c6032671a61bf4c24f16fbe5213138b1aab8d
// registry: a5068dbb9d767f1054812e9a2242964ecd8b22311973d2834569a97a49c96e7f

package templates

// ShellSlotsRegistry lists shell slot contributions by slot name.
var ShellSlotsRegistry = map[string][]string{}
