// Code generated by ggg sync; DO NOT EDIT.
//
// index: 36ff2ca17245198b1f032b2eeabfd50782eb5051e5673553139357e1b7e6acfd
// registry: 629e03faef454aa1531409459e16ff022f94fd920f245b366cd7af4ae41aba0e

package templates

var ShellSlotsRegistry = map[string][]string{}

var ShellSlotRenderers = map[string]any{}

var ShellSlotActive = map[string]func(string) bool{}
